from src.driver.driver import Driver
from src.pages.base_page import BasePage
from src.pages.login_page import LoginPage
from src.pages.register_page import RegisterPage
from src.pages.data_valid.data_validation import DataValidation
from src.tests.test_login import TestLogin
from src.tests.test_register import TestRegister
from src.tests.test_data_validation import TestDataValidation
from src.tests.test_add_to_cart import TestAddToCart
from src.tests.test_checkout import TestCheckout
